from web.template import CompiledTemplate, ForLoop, TemplateResult


# coding: utf-8
def hello (data):
    __lineoffset__ = -4
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<html>\n'])
    extend_([u'<head>\n'])
    extend_([u'<title>Every Vote Counts</title>\n'])
    extend_([u'<script src="/public/javascripts/jquery.min.js"></script><script src="/public/javascripts/modernizr.min.js"></script><script src="/public/javascripts/polymaps.min.js"></script><script src="/public/javascripts/protodata.min.js"></script><script src="/public/javascripts/nns.min.js"></script>\n'])
    extend_([u'<script src="/fips.js"> </script>\n'])
    extend_([u'<link rel="stylesheet" href="/public/stylesheets/colorbrewer.css"/>\n'])
    extend_([u'</head>\n'])
    extend_([u'<body>\n'])
    extend_([u"<h1>Your Vote Counts but Not Equally (each state's residents to electoral votes as a percentage of the national average)</h1>\n"])
    extend_([u'<p>On average every electoral vote represents 573 thousand (Per-vote: 573K) residents. But it varies by state. By <a href="http://www.twitter.com/frankamp">@frankamp</a> data from <a href="https://gist.github.com/4027383">gist</a> fork at <a href="https://github.com/frankamp/every-vote-counts">every-vote-counts</a></p>\n'])
    extend_([u'<p style="font-size: .8em">You\'ll need to be able to hover, so view this on a desktop!</p>\n'])
    extend_([u'<div id="map"></div>\n'])
    extend_([u'<div>\n'])
    extend_([u'        \n'])
    extend_([u'     <script type="text/javascript">\n'])
    extend_([u'\n'])
    extend_([u'var po = org.polymaps;\n'])
    extend_([u'\n'])
    extend_([u'// Compute noniles.\n'])
    extend_([u'var quantile = pv.Scale.quantile()\n'])
    extend_([u'    .quantiles(9)\n'])
    extend_([u'    .domain(pv.values(states))\n'])
    extend_([u'    .range(0, 8);\n'])
    extend_([u'\n'])
    extend_([u'// Date  var format = format.pv.Format.date("%B %e, %Y")\n'])
    extend_([u'\n'])
    extend_([u'\n'])
    extend_([u'var map = po.map()\n'])
    extend_([u'    .container(document.getElementById("map").appendChild(po.svg("svg")))\n'])
    extend_([u'    .center({lat: 40, lon: -95})\n'])
    extend_([u'    .zoomRange([3, 7])\n'])
    extend_([u'    .zoom(5)\n'])
    extend_([u'    .add(po.interact());\n'])
    extend_([u'\n'])
    extend_([u'map.add(po.image()\n'])
    extend_([u'    .url(po.url("http://{S}tile.cloudmade.com"\n'])
    extend_([u'    + "/1a1b06b230af4efdbb989ea99e9841af" // http://cloudmade.com/register\n'])
    extend_([u'    + "/20760/256/{Z}/{X}/{Y}.png")\n'])
    extend_([u'    .hosts(["a.", "b.", "c.", ""])));\n'])
    extend_([u'\n'])
    extend_([u'map.add(po.geoJson()\n'])
    extend_([u'    .url("http://polymaps.appspot.com/state/{Z}/{X}/{Y}.json")\n'])
    extend_([u'    .on("load", load))\n'])
    extend_([u'\n'])
    extend_([u'map.add(po.compass()\n'])
    extend_([u'    .pan("none"));\n'])
    extend_([u'\n'])
    extend_([u'map.container().setAttribute("class", "Blues");\n'])
    extend_([u'\n'])
    extend_([u'function load(e) {\n'])
    extend_([u'  for (var i = 0; i < e.features.length; i++) {\n'])
    extend_([u'    var feature = e.features[i], d = states[feature.data.id.substring(6)];\n'])
    extend_([u'    if (d == undefined) {\n'])
    extend_([u'      feature.element.setAttribute("display", "none");\n'])
    extend_([u'    } else {\n'])
    extend_([u'      feature.element.setAttribute("class", "q" + quantile(d) + "-" + 9);\n'])
    extend_([u'      feature.element.appendChild(po.svg("title").appendChild(\n'])
    extend_([u'          document.createTextNode(feature.data.properties.name + ": "\n'])
    extend_([u'          + d + "% EV: " +electoral[feature.data.properties.name] +\n'])
    extend_([u'          " Pop: "+ pop[feature.data.properties.name] +\n'])
    extend_([u'          "K Per-vote: " + rep[feature.data.properties.name] + "K"))\n'])
    extend_([u'          .parentNode);\n'])
    extend_([u'    }\n'])
    extend_([u'  }\n'])
    extend_([u'}\n'])
    extend_([u'\n'])
    extend_([u'      </script>\n'])
    extend_([u'    \n'])
    extend_([u'<div>\n'])
    extend_([u'<script type="text/javascript">\n'])
    extend_([u'\n'])
    extend_([u'  var _gaq = _gaq || [];\n'])
    extend_([u"  _gaq.push(['_setAccount', 'UA-4160705-6']);\n"])
    extend_([u"  _gaq.push(['_trackPageview']);\n"])
    extend_([u'\n'])
    extend_([u'  (function() {\n'])
    extend_([u"    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n"])
    extend_([u"    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n"])
    extend_([u"    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n"])
    extend_([u'  })();\n'])
    extend_([u'\n'])
    extend_([u'</script>\n'])
    extend_([u'</body>\n'])
    extend_([u'</html>\n'])

    return self

hello = CompiledTemplate(hello, 'templates/hello.html')
join_ = hello._join; escape_ = hello._escape

